insert into country(id, capital, headquarters, language) values(1, 'Berlin', 'Stuttgart', 'German');
insert into country(id, capital, headquarters, language) values(2, 'Berlin', 'Affalterbach', 'German');
insert into country(id, capital, headquarters, language) values(3, 'Berlin', 'Ingolstadt', 'German');
insert into country(id, capital, headquarters, language) values(4, 'Berlin', 'Munich', 'German');
insert into country(id, capital, headquarters, language) values(5, 'Berlin', 'Wolfsburg', 'German');
insert into country(id, capital, headquarters, language) values(6, 'Berlin', 'Rüsselsheim, Hesse', 'German');
insert into country(id, capital, headquarters, language) values(7, 'London', 'Whitley', 'English');
insert into country(id, capital, headquarters, language) values(8, 'London', 'Crewe', 'English');
insert into country(id, capital, headquarters, language) values(9, 'London', 'Surrey', 'English');
insert into country(id, capital, headquarters, language) values(10, 'London', 'Gaydon', 'English');
insert into country(id, capital, headquarters, language) values(11, 'Washington', 'Detroit', 'English');
insert into country(id, capital, headquarters, language) values(12, 'Washington', 'Dearborn', 'English');


insert into car(id, brand, year, country_id) values(1, 'Mercedes-Benz CLA250', 2013, 1);
insert into car(id, brand, year, country_id) values(2, 'Mercedes-Benz C218', 2014, 1);
insert into car(id, brand, year, country_id) values(3, 'Mercedes-Benz CLS Shooting Brake X218', 2014, 1);
insert into car(id, brand, year, country_id) values(4, 'Mercedes-Benz E-Class S212', 2013, 1);
insert into car(id, brand, year, country_id) values(5, 'Mercedes-Benz E-Class A207', 2013, 1);
insert into car(id, brand, year, country_id) values(6, 'Mercedes-Benz E-Class (C207)', 2009, 1);
insert into car(id, brand, year, country_id) values(7, 'Mercedes-Benz S-Class W221', 2009, 1);
insert into car(id, brand, year, country_id) values(8, 'Mercedes-Benz GLE-Class C 292', 2015, 1);
insert into car(id, brand, year, country_id) values(9, 'Mercedes-Benz ML 63 AMG W166', 2011, 2);
insert into car(id, brand, year, country_id) values(10, 'Mercedes-Benz GL 63 AMG', 2015, 2);
insert into car(id, brand, year, country_id) values(11, 'Mercedes-AMG GLE Coupe 63 S', 2015, 2);
insert into car(id, brand, year, country_id) values(12, 'Mercedes-AMG C 63 S', 2015, 2);
insert into car(id, brand, year, country_id) values(13, 'Mercedes-Benz S 63/65 AMG Coupe', 2015, 2);
insert into car(id, brand, year, country_id) values(14, 'Mercedes-AMG GT', 2015, 2);
insert into car(id, brand, year, country_id) values(15, 'Porsche 991 Series', 2012, 1);
insert into car(id, brand, year, country_id) values(16, 'Porsche 997 GT2 RS', 2010, 1);
insert into car(id, brand, year, country_id) values(17, 'Porsche 918', 2013, 1);
insert into car(id, brand, year, country_id) values(18, 'Porsche 911 Carrera', 2013, 1);
insert into car(id, brand, year, country_id) values(19, 'Porsche Panamera Turbo', 2013, 1);
insert into car(id, brand, year, country_id) values(20, 'Porsche Boxster', 2012, 1);
insert into car(id, brand, year, country_id) values(21, 'Audi A4/Audi A4 Avant', 2007, 3);
insert into car(id, brand, year, country_id) values(22, 'Audi A6', 2011, 3);
insert into car(id, brand, year, country_id) values(23, 'Audi A7 Sportback', 2010, 3);
insert into car(id, brand, year, country_id) values(24, 'Audi A8', 2010, 3);
insert into car(id, brand, year, country_id) values(25, 'Audi TT', 2006, 3);
insert into car(id, brand, year, country_id) values(26, 'Audi A5', 2007, 3);
insert into car(id, brand, year, country_id) values(27, 'Audi R8 Spyder', 2008, 3);
insert into car(id, brand, year, country_id) values(28, 'Audi R8 GT', 2010, 3);
insert into car(id, brand, year, country_id) values(29, 'Audi e-tron', 2015, 3);
insert into car(id, brand, year, country_id) values(30, 'BMW F80 Sedan', 2013, 4);
insert into car(id, brand, year, country_id) values(31, 'BMW F82 Coupé', 2013, 4);
insert into car(id, brand, year, country_id) values(32, 'BMW F10 Saloon', 2011, 4);
insert into car(id, brand, year, country_id) values(33, 'BMW F06/12/13', 2012, 4);
insert into car(id, brand, year, country_id) values(34, 'BMW F15 SAV', 2014, 4);
insert into car(id, brand, year, country_id) values(35, 'BMW F16 SAV', 2015, 4);
insert into car(id, brand, year, country_id) values(36, 'Volkswagen Golf', 2014, 5);
insert into car(id, brand, year, country_id) values(37, 'Volkswagen Passat', 2014, 5);
insert into car(id, brand, year, country_id) values(38, 'Opel Antara', 2015, 6);
insert into car(id, brand, year, country_id) values(39, 'Opel Astra', 2015, 6);
insert into car(id, brand, year, country_id) values(40, 'Opel Astra GTC', 2015, 6);
insert into car(id, brand, year, country_id) values(41, 'Jaguar XJ', 2009, 7);
insert into car(id, brand, year, country_id) values(42, 'Jaguar XE', 2015, 7);
insert into car(id, brand, year, country_id) values(43, 'Jaguar RSR XKR GT2', 2010, 7);
insert into car(id, brand, year, country_id) values(44, 'Jaguar F-Pace', 2016, 7);
insert into car(id, brand, year, country_id) values(45, 'Jaguar C-X17', 2015, 7);
insert into car(id, brand, year, country_id) values(46, 'Bentley Azure', 2002, 8);
insert into car(id, brand, year, country_id) values(47, 'Bentley Continental GT', 2011, 8);
insert into car(id, brand, year, country_id) values(48, 'Bentley Supersports', 2009, 8);
insert into car(id, brand, year, country_id) values(49, 'Bentley Continental GTZ', 2012, 8);
insert into car(id, brand, year, country_id) values(50, 'McLaren GT', 2011, 9);
insert into car(id, brand, year, country_id) values(51, 'McLaren 570S', 2015, 9);
insert into car(id, brand, year, country_id) values(52, 'McLaren 675LT', 2015, 9);
insert into car(id, brand, year, country_id) values(53, 'McLaren F1', 2013, 9);
insert into car(id, brand, year, country_id) values(54, 'Aston Martin Vulcan', 2015, 10);
insert into car(id, brand, year, country_id) values(55, 'Aston Martin DB10', 2015, 10);
insert into car(id, brand, year, country_id) values(56, 'Aston Martin CC100', 2013, 10);
insert into car(id, brand, year, country_id) values(57, 'Aston Martin Vanquish', 2012, 10);
insert into car(id, brand, year, country_id) values(58, 'Aston Martin Vantage GT12', 2012, 10);
insert into car(id, brand, year, country_id) values(59, 'Aston Martin DB9', 2015, 10);
insert into car(id, brand, year, country_id) values(60, 'Chevrolet Camaro', 2010, 11);
insert into car(id, brand, year, country_id) values(61, 'Chevrolet Cruze', 2013, 11);
insert into car(id, brand, year, country_id) values(62, 'Chevrolet Corvette Stingray C7', 2014, 11);
insert into car(id, brand, year, country_id) values(63, 'Ford Mustang GT', 2010, 12);
